<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWPF>true</UseWPF>
    <AssemblyName>Prometheus.Desktop</AssemblyName>
    <ApplicationIcon>Prometheus.ico</ApplicationIcon>
	<ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Prometheus.ico" />
    <Resource Include="Prometheus.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HandyControl" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="Prism.DryIoc" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Prometheus.Core\Prometheus.Core.csproj" />
    <ProjectReference Include="..\Prometheus.Modules.Home\Prometheus.Modules.Home.csproj" />
    <ProjectReference Include="..\Prometheus.Modules.Inventory\Prometheus.Modules.Inventory.csproj" />
    <ProjectReference Include="..\Prometheus.Modules.Match\Prometheus.Modules.Match.csproj" />
    <ProjectReference Include="..\Prometheus.Modules.Search\Prometheus.Modules.Search.csproj" />
    <ProjectReference Include="..\Prometheus.Modules.Setting\Prometheus.Modules.Setting.csproj" />
    <ProjectReference Include="..\Prometheus.Modules.Summoner\Prometheus.Modules.Summoner.csproj" />
    <ProjectReference Include="..\Prometheus.Modules.Utility\Prometheus.Modules.Utility.csproj" />
    <ProjectReference Include="..\Prometheus.Shared\Prometheus.Shared.csproj" />
    <ProjectReference Include="..\Prometheus.Update\Prometheus.Update.csproj" />
    <ProjectReference Include="..\Services\Prometheus.Services.Interfaces\Prometheus.Services.Interfaces.csproj" />
    <ProjectReference Include="..\Services\Prometheus.Services\Prometheus.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyMetadata Include="GitHubRepositoryOwner" Value="$(GitHubRepositoryOwner)" />
    <AssemblyMetadata Include="GitHubRepositoryName" Value="$(GitHubRepositoryName)" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>
